### PR TITLE
[WIP] Add MQTT config

### PR DESCRIPTION
**Pull request by jbaudoux**

### CODE REVIEW

**Comment by salbahra** [comment]
I don’t think we will be changing the currently used option index for the new sensors, etc. I would suggest MQTT go after those items and not try to push other items to new values.

**Comment by jbaudoux** [comment]
@salbahra Thanks for the review. Then latest commit can be reverted. May I suggest you to not develop in master branch? Because there is currently a mismatch between the Firmware master branch and this App one. And it would also be nice to tag the versions. That will help contributors ;-)

**Comment by salbahra** [comment]
I can try :) the app work for 2.1.9 was done outside of master to be fair and merged in recently.

Thanks for your PR, once fixed up we can def try to get this merged in.

**Comment by jbaudoux** [comment]
replaced by https://github.com/OpenSprinkler/OpenSprinkler-App/pull/86

**Pull request closed without merging**
