### PR TITLE
add some staticts from the log data in Log menu

### PR DESCRIPTION
**Pull request by littleprojects**
Graph: total running time per week over all log data
Graph: mean waterlevel per wekk over all log data
Graph: mean running time per week day
Table: total running time per station and total running time over all
stations

i need you help with the css. maybe some radiobuttons to switch between the graphs

### CODE REVIEW

**Comment by salbahra** [comment]
Thank you again for the pull request. I did try to use your current branch without success (some errors and the graph never loads). I did some investigation and the graphing library you are using makes use of inline javascript. This prevents it from loading in some environment it seems.

Also, I did start adding some statistical data and planned on showing this at the top of the table view. If you don't mind, I think I am going to elaborate more on the method I had in mind. I will keep this open until what I had in mind is added and take another look after.

**Comment by littleprojects** [comment]
Okay, 

I check what's wrong with me code. Hmmm. :/

**Comment by salbahra** [comment]
I am getting ready to merge some functions that will gather the stats while doing the data sorting loops to prevent an extra set of loops.

Currently, I am writing a function to append a statistic box at the top of all log pages showing a brief summary of the selected date range. I have included the same stats you have made: total runtime, mean water level, and total running time. Do you think I should do the same thing and show this data as "per week" instead of just the average over the selected range?

I did get your code to work in Firefox and it looks nice however I would like to see it work in all browsers before choosing this library. Also, I would like to use the graphing library for more than just the stats otherwise I don't think it's worth including it due to size vs benefit.

**Comment by littleprojects** [comment]
Hi, 

i used the graph lib from http://www.chartjs.org/ . It should work with all browser... And the Projectpage work on IE, Firefox and chrome... Maybe something with the canvas element? Please download the lib and try the examples.

**Comment by salbahra** [comment]
The library looks and works great so it must be a conflict with how my permissions are set up. I will take a look and let you know.

**Pull request closed without merging**
