### PR TITLE
Restore ability to select PWS when providing an API key

### PR DESCRIPTION
**Pull request by salbahra**
Adds support to view and select personal weather stations (PWS) when provided an API key. This is is for PWS owners only.

This PR also updates all packages to the latest version and changes all indentation to tabs for all files (due to inconsistencies in the PR diff). Due to this, please ignore whitespace when diffing. Github has an option for this under the gear icon at the top. 

This will be used in conjunction with https://github.com/OpenSprinkler/OpenSprinkler-Weather/pull/70 and https://github.com/OpenSprinkler/OpenSprinkler-Weather/pull/72.

### CODE REVIEW

**Comment by salbahra** [comment]
@Derpthemeus Feedback on the following:

1) For the location, I believe we are using the coordinates for location here: https://github.com/OpenSprinkler/OpenSprinkler-App/pull/63/files#diff-60f1f7e7ccc2f7144af40899924f40f0R3859 and we set the `wto.pws` here: https://github.com/OpenSprinkler/OpenSprinkler-App/pull/63/files#diff-60f1f7e7ccc2f7144af40899924f40f0R3849.

1) I can add that feedback in the help option once we add ETo

1) WUnderground API returns an HTTP error but it also returns a payload which has an errors array and each error has a message and a code. The `done` is an alias for `success` so we actually need to add a fail handler instead of checking the reply for errors in success. More specifically, we don't handle a fail condition (nothing to do) so simply deleting this check should suffice. Fixed now.

1) This was mostly because of translation reasons and because Dark Sky isn't out yet.

**Comment by salbahra** [comment]
@Derpthemeus thank you for clarifying the first point! I have removed this input method now (typing `pws:STATIONID`).

**Comment by salbahra** [comment]
For the second point, this is where I think we would add that information:
Screen Shot 2019-07-09 at 12 03 27 PM

**Comment by Derpthemeus** [comment]
That should be perfect. After that has been added, will we need to get the message translated before we're ready to merge?

**Comment by salbahra** [comment]
@Derpthemeus I think we should add that into the ETo PR as that's not been introduced yet, imo. Addressing localization is outside the scope of this PR but something we need to address now that getlocalization.com is offline.

**Pull request merged**
